blog/urls.py
from django.urls import path
from blog.views import all_post_view, category_view, tag_view, post_detail_view

app_name = 'blog'

urlpatterns = [
    path('', all_post_view, name='all_post_view'),
    path('category/<slug:category_slug>/', category_view, name='category_view'),
    path('tag/<slug:tag_slug>/', tag_view, name='tag_view'),

    path('category/<slug:category_slug>/<slug:post_slug>/', post_detail_view, name='post_detail_view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# My Views:
from config.views import logout_view
from page.views import home_view

urlpatterns = [
    path('', home_view, name='home'),

    # Pages:
    path('page/', include('page.urls', namespace='page')),

    # Todo Apps:
    path('todo/', include('todo.urls', namespace='todo')),

    # Blog Apps:
    path('blog/', include('blog.urls', namespace='blog')),

    # Auth:
    path('account/logout/', logout_view, name='logout_view'),

    # TinyMCE:
    path('tinymce/', include('tinymce.urls')),
    
    # Admin:
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DjangoMania</title>
    {% comment %} bootstrap {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
  <body>
    {% include 'core/navbar.html' %}

      {% block container-fluid %}
      {% endblock container-fluid %}

    <div class="container my-5">
    {% block container %}
    {% endblock container %}
    </div>    
    {% comment %} bootstrap js {% endcomment %}
    {% include 'core/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

templates/core/footer.html
<div class="bg-dark py-5 mt-5">
    <div class="container">
        <div class="col">
            <h1 class="text-light">DjangoMania</h1>
        </div>
    </div>
</div>

templates/core/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="/">DjangoMania</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Ana Sehife</a>
          </li>

          {% comment %} {% if request.user.is_authenticated %} {% endcomment %}
             <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Todo Kateqoriyalar
            </a>
            <ul class="dropdown-menu">
              {% for category in global_todo_categories %}
              <li>
                {% comment %} <a class="dropdown-item" href="{% url 'category_view' category_slug=category.slug %}">{{ category.title }}</a> {% endcomment %}
                <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.title }}</a>
              </li>
              {% endfor %}
            </ul>
          </li>
          {% comment %} {% endif %} {% endcomment %}

          {% for page in global_pages %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ page.get_absolute_url }}">{{ page.title }}</a>
          </li>
          {% endfor %}

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'blog:all_post_view' %}">Bloq</a>
          </li>

          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'logout_view' %}">Sessiyani bitir</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>